# fly.toml file generated for beamscene on 2023-04-14T01:40:09-04:00

app = "beamscene"
kill_signal = "SIGTERM"
kill_timeout = 5
primary_region = "yyz"

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "beamscene.fly.dev"
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
