name: docs

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  ELIXIR_VERSION: 1.14.2
  OTP_VERSION: 25

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}

      - name: Retrieve Mix Dependencies Cache
        uses: actions/cache/restore@v3
        id: mix-cache
        with:
          path: |
            _build
            deps
          key: ${{ runner.os }}-${{ env.OTP_VERSION }}-${{ env.ELIXIR_VERSION }}-mix-${{ hashFiles('**/mix.lock') }}

      - name: Install Mix Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get --only dev

      - name: Build Docs
        run: mix docs

      - name: Upload Docs
        uses: actions/upload-pages-artifact@v1
        with:
          path: doc
  deploy:
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: actions/deploy-pages@v1
